name: Build and publish demo

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/cd-publish-demo.yaml
      - web/**
      - .yarn
      - .yarnrc.yml
      - biome.jsonc
      - package.json
      - tsconfig.json
      - vite.config.ts
      - yarn.lock

permissions:
  contents: read

jobs:
  build:
    name: Build demo
    runs-on: ubuntu-latest

    permissions:
      packages: read # Download demo data

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 22
          cache: yarn

      - name: Setup oras
        uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6 # v1.2.4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Log in to GHCR
        run: echo "$GITHUB_TOKEN" | oras login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Download demo data
        working-directory: web/public/assets
        run: oras pull ghcr.io/alexgustafsson/cupdate/demo:latest

      - name: Log out from GHCR
        if: always()
        run: oras logout ghcr.io 2>/dev/null || true

      - name: Build web
        env:
          VITE_DEMO_MODE: "true"
          VITE_BASE_PATH: "/cupdate"
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: internal/web/public

  deploy:
    name: Deploy demo
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      pages: write # Deploy to pages
      id-token: write # Verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e #v4.0.5
