name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci-test.yaml
      - cmd/**
      - internal/**
      - Dockerfile
      - go.*
      - web/**
      - .yarn
      - .yarnrc.yml
      - biome.jsonc
      - package.json
      - tsconfig.json
      - vite.config.ts
      - yarn.lock

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
          cache: yarn

      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: |
          yarn install --immutable
          go mod download

      - name: Run go tests
        env:
          # Use the toolchain specified in go.mod, or newer
          GOTOOLCHAIN: auto
        run: go test -race -short -v ./...

      - name: Run go Zot integration tests
        env:
          # Use the toolchain specified in go.mod, or newer
          GOTOOLCHAIN: auto
        run: go test -v -run TestIntegrationClientZot ./...

      - name: Run web tests
        run: yarn run test
