name: GitHub Actions Security Analysis

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/zizmor.yaml
      - .github/workflows/**/*.yaml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/zizmor.yaml
      - .github/workflows/**/*.yaml
  schedule:
    # Some random-ish cron to help with GitHub Actions scheduling, once a week
    - cron: 29 11 * * 2

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Write events
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1

      - name: Run zizmor
        run: uvx zizmor --format=sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 #v3.29.5
        with:
          sarif_file: results.sarif
          category: zizmor
